services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # All DB's will be created by deploy/init.sql file in docker-entrypoint
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  rabbit:
    image: rabbitmq:4.3-management
    container_name: billing_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pg_data:
  rabbitmq_data:
  redis:
    driver: local