### Пополнение (Создаст счет или добавит денег)
POST http://localhost:8080/deposit
Content-Type: application/json

{
  "amount": 5000
}

### Списание (Проверь списание 1000 и попытку списать 999999)
POST http://localhost:8080/withdraw
Content-Type: application/json

{
  "amount": 1000
}